### ISSUE TITLE
Results stick on page even when user clicks elsewhere.

### ISSUE THREAD

**Issue by meganbeck** [jchristopher/searchwp-live-ajax-search#126] opened 2020-04-12 23:41 UTC
It would be great to be able to apply a filter for search results to remain displayed even when user clicks elsewhere on the page. They currently disappear anytime another area of page is clicked.

**Comment by jchristopher** [comment] 2020-04-13 00:14
Hi @meganbeck you can do that by customizing the `results_destroy_on_blur` property.

You can either filter the config itself e.g.

```php
add_filter( 'searchwp_live_search_configs', function( $configs ) {
	$configs['default']['destroy_on_blur'] = false;

	return $configs;
} );
```

or if you're manually working with an `input` you can pass it in as a data attribute e.g.

```html
<input type="text" 
       name="s"
       data-swplive="true"
       data-swpconfig="{'results_destroy_on_blur': false}"
/>
```

Duplicate of https://github.com/jchristopher/searchwp-live-ajax-search/issues/119
Duplicate of https://github.com/jchristopher/searchwp-live-ajax-search/issues/96

**Closed by jchristopher** 2020-04-13 00:14 UTC
