### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by mikekrueger** [jchristopher/searchwp-live-ajax-search#19] opened 2014-11-13 15:11 UTC
I have installed WPSearch, LIKE terms and Live Ajax Search. Have everything working except for the Live Ajax Search piece. When I inspect my source, a form generated by get_search_form() correctly adds data-swplive="true" to the input field. However, I don't see any ajax calls, errors, or anything...making it hard to troubleshoot. Wondering if there are any additional details I can provide to get an idea of what might be going on. Theme is a custom child theme over the barebones HTML5 reset theme. Thank you.

**Comment by jchristopher** [comment] 2015-07-26 22:49
Hi Mike, I apologize for the delay in getting to this Issue. I'm hoping you were able to open a SearchWP support request to get the issue resolved quickly but if not you can absolutely do that now. Going to close this for the time being simply because the issue is old enough but I'm happy to re-open it. Submitting a ticket to SearchWP directly will definitely get you an answer very quickly.

**Closed by jchristopher** 2015-07-26 22:49 UTC
